"""Initial schema

Revision ID: a1bfafe130ce
Revises:
Create Date: 2026-08-29 14:15:17.799325

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a1bfafe130ce"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("customer_type", sa.String(length=32), nullable=False),
        sa.Column("country", sa.String(length=64), nullable=False),
        sa.Column("city", sa.String(length=128), nullable=True),
        sa.Column("language", sa.String(length=32), nullable=False),
        sa.Column("preferred_channel", sa.String(length=32), nullable=False),
        sa.Column("customer_since", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payment_reliability_score", sa.Numeric(precision=6, scale=5), nullable=True),
        sa.Column("avg_payment_delay_days", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("lifetime_value", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("active_subscriptions", sa.Integer(), nullable=False),
        sa.Column("communication_opt_out", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "active_subscriptions >= 0", name="ck_customers_active_subscriptions_non_negative"
        ),
        sa.CheckConstraint("lifetime_value >= 0", name="ck_customers_lifetime_value_non_negative"),
        sa.CheckConstraint(
            "payment_reliability_score IS NULL OR (payment_reliability_score >= 0 AND payment_reliability_score <= 1)",
            name="ck_customers_reliability_score_range",
        ),
        sa.PrimaryKeyConstraint("customer_id"),
    )
    op.create_table(
        "model_metadata",
        sa.Column("model_id", sa.Uuid(), nullable=False),
        sa.Column("model_name", sa.String(length=64), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("model_type", sa.String(length=64), nullable=False),
        sa.Column("feature_schema_version", sa.String(length=64), nullable=False),
        sa.Column("training_dataset_hash", sa.String(length=128), nullable=False),
        sa.Column("artifact_uri", sa.Text(), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("model_id"),
        sa.UniqueConstraint("model_name", "model_version", name="uq_model_name_version"),
    )
    op.create_table(
        "simulation_runs",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("strategy", sa.String(length=64), nullable=False),
        sa.Column("scenario", sa.String(length=64), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("dataset_version", sa.String(length=64), nullable=False),
        sa.Column("dataset_hash", sa.String(length=128), nullable=False),
        sa.Column("model_versions", postgresql.JSONB(astext_type=Text()), nullable=True),
        sa.Column("policy_version", sa.String(length=64), nullable=False),
        sa.Column("configuration_hash", sa.String(length=128), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_table(
        "invoices",
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("issue_date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("days_overdue", sa.Integer(), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("amount > 0", name="ck_invoices_amount_positive"),
        sa.CheckConstraint("days_overdue >= 0", name="ck_invoices_days_overdue_non_negative"),
        sa.CheckConstraint("due_date >= issue_date", name="ck_invoices_due_after_issue"),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.customer_id"],
        ),
        sa.PrimaryKeyConstraint("invoice_id"),
    )
    op.create_index("idx_invoices_customer", "invoices", ["customer_id"], unique=False)
    op.create_index("idx_invoices_status_due", "invoices", ["status", "due_date"], unique=False)
    op.create_table(
        "model_runs",
        sa.Column("model_run_id", sa.Uuid(), nullable=False),
        sa.Column("model_id", sa.Uuid(), nullable=False),
        sa.Column("simulation_run_id", sa.Uuid(), nullable=True),
        sa.Column("inference_count", sa.Integer(), nullable=False),
        sa.Column("average_latency_ms", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["model_metadata.model_id"],
        ),
        sa.ForeignKeyConstraint(
            ["simulation_run_id"],
            ["simulation_runs.run_id"],
        ),
        sa.PrimaryKeyConstraint("model_run_id"),
    )
    op.create_table(
        "recovery_cases",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("amount_at_risk", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("risk_score", sa.Numeric(precision=6, scale=5), nullable=True),
        sa.Column("root_cause", sa.String(length=64), nullable=True),
        sa.Column("root_cause_confidence", sa.Numeric(precision=6, scale=5), nullable=True),
        sa.Column("recovery_probability", sa.Numeric(precision=6, scale=5), nullable=True),
        sa.Column("recommended_action", sa.String(length=64), nullable=True),
        sa.Column("expected_recovery", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("expected_net_recovery", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("decision_confidence", sa.Numeric(precision=6, scale=5), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("escalation_required", sa.Boolean(), nullable=False),
        sa.Column("stop_reason", sa.String(length=128), nullable=True),
        sa.Column("workflow_run_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "amount_at_risk >= 0", name="ck_recovery_cases_amount_at_risk_non_negative"
        ),
        sa.CheckConstraint(
            "decision_confidence IS NULL OR (decision_confidence >= 0 AND decision_confidence <= 1)",
            name="ck_recovery_cases_decision_confidence_range",
        ),
        sa.CheckConstraint(
            "expected_net_recovery IS NULL OR expected_net_recovery >= 0",
            name="ck_recovery_cases_expected_net_recovery_non_negative",
        ),
        sa.CheckConstraint(
            "expected_recovery IS NULL OR expected_recovery >= 0",
            name="ck_recovery_cases_expected_recovery_non_negative",
        ),
        sa.CheckConstraint(
            "recovery_probability IS NULL OR (recovery_probability >= 0 AND recovery_probability <= 1)",
            name="ck_recovery_cases_recovery_probability_range",
        ),
        sa.CheckConstraint(
            "risk_score IS NULL OR (risk_score >= 0 AND risk_score <= 1)",
            name="ck_recovery_cases_risk_score_range",
        ),
        sa.CheckConstraint(
            "root_cause_confidence IS NULL OR (root_cause_confidence >= 0 AND root_cause_confidence <= 1)",
            name="ck_recovery_cases_root_cause_confidence_range",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.customer_id"],
        ),
        sa.PrimaryKeyConstraint("case_id"),
    )
    op.create_index("idx_cases_customer", "recovery_cases", ["customer_id"], unique=False)
    op.create_index(
        "idx_cases_source", "recovery_cases", ["source_type", "source_id"], unique=False
    )
    op.create_index(
        "idx_cases_status_priority",
        "recovery_cases",
        ["status", sa.literal_column("expected_net_recovery DESC")],
        unique=False,
    )
    op.create_index(
        "uq_active_recovery_case",
        "recovery_cases",
        ["source_type", "source_id"],
        unique=True,
        postgresql_where="status NOT IN ('CLOSED','CANCELLED')",
    )
    op.create_table(
        "simulation_results",
        sa.Column("result_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("total_events", sa.Integer(), nullable=False),
        sa.Column("total_cases", sa.Integer(), nullable=False),
        sa.Column("revenue_at_risk", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("gross_recovered", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("intervention_cost", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("net_recovered", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("recovery_rate", sa.Numeric(precision=8, scale=5), nullable=False),
        sa.Column("incremental_revenue", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("policy_violations", sa.Integer(), nullable=False),
        sa.Column("duplicate_actions", sa.Integer(), nullable=False),
        sa.Column("escalations", sa.Integer(), nullable=False),
        sa.Column("stopped_cases", sa.Integer(), nullable=False),
        sa.Column("recovered_cases", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["simulation_runs.run_id"],
        ),
        sa.PrimaryKeyConstraint("result_id"),
    )
    op.create_table(
        "subscriptions",
        sa.Column("subscription_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("plan", sa.String(length=64), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("billing_cycle", sa.String(length=32), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("next_billing_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("amount > 0", name="ck_subscriptions_amount_positive"),
        sa.CheckConstraint(
            "next_billing_date >= start_date", name="ck_subscriptions_billing_after_start"
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.customer_id"],
        ),
        sa.PrimaryKeyConstraint("subscription_id"),
    )
    op.create_table(
        "audit_events",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("actor_type", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.String(length=128), nullable=True),
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("correlation_id", sa.String(length=255), nullable=False),
        sa.Column("input_snapshot", postgresql.JSONB(astext_type=Text()), nullable=True),
        sa.Column("decision", postgresql.JSONB(astext_type=Text()), nullable=True),
        sa.Column("policy_result", postgresql.JSONB(astext_type=Text()), nullable=True),
        sa.Column("execution_result", postgresql.JSONB(astext_type=Text()), nullable=True),
        sa.Column("outcome", postgresql.JSONB(astext_type=Text()), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["recovery_cases.case_id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        "idx_audit_case_time",
        "audit_events",
        ["case_id", sa.literal_column("event_time DESC")],
        unique=False,
    )
    op.create_index("idx_audit_correlation", "audit_events", ["correlation_id"], unique=False)
    op.create_table(
        "interactions",
        sa.Column("interaction_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("recovery_case_id", sa.Uuid(), nullable=True),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("customer_response", sa.Text(), nullable=True),
        sa.Column("intent", sa.String(length=64), nullable=True),
        sa.Column("promise_to_pay", sa.Boolean(), nullable=True),
        sa.Column("promised_date", sa.Date(), nullable=True),
        sa.Column("llm_confidence", sa.Numeric(precision=6, scale=5), nullable=True),
        sa.Column("generation_method", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.customer_id"],
        ),
        sa.ForeignKeyConstraint(
            ["recovery_case_id"],
            ["recovery_cases.case_id"],
        ),
        sa.PrimaryKeyConstraint("interaction_id"),
    )
    op.create_index(
        "idx_interactions_case_time",
        "interactions",
        ["recovery_case_id", sa.literal_column("occurred_at DESC")],
        unique=False,
    )
    op.create_index(
        "idx_interactions_customer_time",
        "interactions",
        ["customer_id", sa.literal_column("occurred_at DESC")],
        unique=False,
    )
    op.create_table(
        "interventions",
        sa.Column("intervention_id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("action_type", sa.String(length=64), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cost", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("policy_decision", sa.String(length=16), nullable=False),
        sa.Column("policy_reason", sa.Text(), nullable=True),
        sa.Column("policy_version", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("provider_reference", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("attempt_number >= 1", name="ck_interventions_attempt_number_min"),
        sa.CheckConstraint("cost >= 0", name="ck_interventions_cost_non_negative"),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["recovery_cases.case_id"],
        ),
        sa.PrimaryKeyConstraint("intervention_id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_table(
        "payments",
        sa.Column("payment_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("subscription_id", sa.Uuid(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payment_method", sa.String(length=32), nullable=False),
        sa.Column("gateway", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("failure_code", sa.String(length=32), nullable=True),
        sa.Column("failure_reason", sa.String(length=64), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=True),
        sa.Column("provider_reference", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("amount > 0", name="ck_payments_amount_positive"),
        sa.CheckConstraint("retry_count >= 0", name="ck_payments_retry_count_non_negative"),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.customer_id"],
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.subscription_id"],
        ),
        sa.PrimaryKeyConstraint("payment_id"),
    )
    op.create_index(
        "idx_payments_customer_time",
        "payments",
        ["customer_id", sa.literal_column("occurred_at DESC")],
        unique=False,
    )
    op.create_index(
        "idx_payments_gateway_time",
        "payments",
        ["gateway", sa.literal_column("occurred_at DESC")],
        unique=False,
    )
    op.create_index("idx_payments_status", "payments", ["status"], unique=False)
    op.create_index(
        "uq_payments_idempotency",
        "payments",
        ["idempotency_key"],
        unique=True,
        postgresql_where="idempotency_key IS NOT NULL",
    )
    op.create_table(
        "outcomes",
        sa.Column("outcome_id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("intervention_id", sa.Uuid(), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("amount_recovered", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("failure_reason", sa.String(length=128), nullable=True),
        sa.Column("payment_status_after", sa.String(length=32), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "amount_recovered >= 0", name="ck_outcomes_amount_recovered_non_negative"
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["recovery_cases.case_id"],
        ),
        sa.ForeignKeyConstraint(
            ["intervention_id"],
            ["interventions.intervention_id"],
        ),
        sa.PrimaryKeyConstraint("outcome_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("outcomes")
    op.drop_index(
        "uq_payments_idempotency",
        table_name="payments",
        postgresql_where="idempotency_key IS NOT NULL",
    )
    op.drop_index("idx_payments_status", table_name="payments")
    op.drop_index("idx_payments_gateway_time", table_name="payments")
    op.drop_index("idx_payments_customer_time", table_name="payments")
    op.drop_table("payments")
    op.drop_table("interventions")
    op.drop_index("idx_interactions_customer_time", table_name="interactions")
    op.drop_index("idx_interactions_case_time", table_name="interactions")
    op.drop_table("interactions")
    op.drop_index("idx_audit_correlation", table_name="audit_events")
    op.drop_index("idx_audit_case_time", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_table("subscriptions")
    op.drop_table("simulation_results")
    op.drop_index(
        "uq_active_recovery_case",
        table_name="recovery_cases",
        postgresql_where="status NOT IN ('CLOSED','CANCELLED')",
    )
    op.drop_index("idx_cases_status_priority", table_name="recovery_cases")
    op.drop_index("idx_cases_source", table_name="recovery_cases")
    op.drop_index("idx_cases_customer", table_name="recovery_cases")
    op.drop_table("recovery_cases")
    op.drop_table("model_runs")
    op.drop_index("idx_invoices_status_due", table_name="invoices")
    op.drop_index("idx_invoices_customer", table_name="invoices")
    op.drop_table("invoices")
    op.drop_table("simulation_runs")
    op.drop_table("model_metadata")
    op.drop_table("customers")
    # ### end Alembic commands ###
